backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - label: "Projects"
    name: "project"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "project"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "thumbnail", widget: "image"}
      - {label: "Link to URL", name: "url", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/home.md"
        fields: 
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Intro", name: "intro", widget: "markdown"}
          - label: "Intro"
            name: "intro"
            widget: "markdown"
      - label: "About Page"
        name: "about"
        file: "content/about.md"
        fields: 
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Intro", name: "intro", widget: "text"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Photo", name: "photo", widget: "image"}
      - label: "Skills Page"
        name: "skills"
        file: "content/skills.md"
        fields: 
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Skills Info", name: "skillsInfo", widget: "markdown"}
          - label: "skills"
            name: "Skills"
            widget: "list"
            fields: 
              - {label: "Skill Name", name: "skillName", widget: "string"}
              - {label: "Skill Icon Name", name: "skillIconName", widget: "string"}