backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - label: "Projects"
    name: "projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "project"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "thumbnail", widget: "image"}
      - {label: "Link to URL", name: "url", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
      - name: "about"
        file: "content/home.yml"
        fields: 
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: "intro"
            name: "Intro"
            widget: markdown
      - label: "About Page"
      - name: "about"
        file: "content/about.yml"
        fields: 
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: "zach"
            name: "Zach"
            widget: list
            fields: 
              - {label: Name, name: name, widget: string}
              - {label: Title, name: title, widget: string}
              - {label: Photo, name: photo, widget: image}
      - label: "Skills Page"
        name: "skills"
        file: "content/skills.yml"
        fields: 
          - {label: Name, name: name, widget: string}
          - {label: Info, name: info, widget: markdown}
          - label: skills
            name: Skills
            widget: list